# https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # must match the fields below: <plural>.<group>
  name: nfsvolumes.samplecrd.k8s.io
spec:
  # REST API /apis/<group><version>
  group: samplecrd.k8s.io
  versions:
    - name: v1
      served: true
      storage: true # one and only one must't be marked as the storage version
  names:
    kind: Nfsvolume
    plural: nfsvolumes
    shortNames:
      - nv
  scope: Namespaced # Namespaced or Cluster

