/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	samplecrdv1 "nfs-controller/pkg/apis/samplecrd/v1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNFSVolumes implements NFSVolumeInterface
type FakeNFSVolumes struct {
	Fake *FakeSamplecrdV1
	ns   string
}

var nfsvolumesResource = schema.GroupVersionResource{Group: "samplecrd.k8s.io", Version: "v1", Resource: "nfsvolumes"}

var nfsvolumesKind = schema.GroupVersionKind{Group: "samplecrd.k8s.io", Version: "v1", Kind: "NFSVolume"}

// Get takes name of the nFSVolume, and returns the corresponding nFSVolume object, and an error if there is any.
func (c *FakeNFSVolumes) Get(name string, options v1.GetOptions) (result *samplecrdv1.NFSVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nfsvolumesResource, c.ns, name), &samplecrdv1.NFSVolume{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecrdv1.NFSVolume), err
}

// List takes label and field selectors, and returns the list of NFSVolumes that match those selectors.
func (c *FakeNFSVolumes) List(opts v1.ListOptions) (result *samplecrdv1.NFSVolumeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nfsvolumesResource, nfsvolumesKind, c.ns, opts), &samplecrdv1.NFSVolumeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &samplecrdv1.NFSVolumeList{ListMeta: obj.(*samplecrdv1.NFSVolumeList).ListMeta}
	for _, item := range obj.(*samplecrdv1.NFSVolumeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nFSVolumes.
func (c *FakeNFSVolumes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nfsvolumesResource, c.ns, opts))

}

// Create takes the representation of a nFSVolume and creates it.  Returns the server's representation of the nFSVolume, and an error, if there is any.
func (c *FakeNFSVolumes) Create(nFSVolume *samplecrdv1.NFSVolume) (result *samplecrdv1.NFSVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nfsvolumesResource, c.ns, nFSVolume), &samplecrdv1.NFSVolume{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecrdv1.NFSVolume), err
}

// Update takes the representation of a nFSVolume and updates it. Returns the server's representation of the nFSVolume, and an error, if there is any.
func (c *FakeNFSVolumes) Update(nFSVolume *samplecrdv1.NFSVolume) (result *samplecrdv1.NFSVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nfsvolumesResource, c.ns, nFSVolume), &samplecrdv1.NFSVolume{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecrdv1.NFSVolume), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNFSVolumes) UpdateStatus(nFSVolume *samplecrdv1.NFSVolume) (*samplecrdv1.NFSVolume, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(nfsvolumesResource, "status", c.ns, nFSVolume), &samplecrdv1.NFSVolume{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecrdv1.NFSVolume), err
}

// Delete takes name of the nFSVolume and deletes it. Returns an error if one occurs.
func (c *FakeNFSVolumes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(nfsvolumesResource, c.ns, name), &samplecrdv1.NFSVolume{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNFSVolumes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nfsvolumesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &samplecrdv1.NFSVolumeList{})
	return err
}

// Patch applies the patch and returns the patched nFSVolume.
func (c *FakeNFSVolumes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *samplecrdv1.NFSVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nfsvolumesResource, c.ns, name, pt, data, subresources...), &samplecrdv1.NFSVolume{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecrdv1.NFSVolume), err
}
