/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	samplecrdv1 "nfs-controller/pkg/apis/samplecrd/v1"
	versioned "nfs-controller/pkg/client/clientset/versioned"
	internalinterfaces "nfs-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "nfs-controller/pkg/client/listers/samplecrd/v1"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NFSVolumeInformer provides access to a shared informer and lister for
// NFSVolumes.
type NFSVolumeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.NFSVolumeLister
}

type nFSVolumeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewNFSVolumeInformer constructs a new informer for NFSVolume type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNFSVolumeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNFSVolumeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredNFSVolumeInformer constructs a new informer for NFSVolume type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNFSVolumeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SamplecrdV1().NFSVolumes(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SamplecrdV1().NFSVolumes(namespace).Watch(options)
			},
		},
		&samplecrdv1.NFSVolume{},
		resyncPeriod,
		indexers,
	)
}

func (f *nFSVolumeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNFSVolumeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *nFSVolumeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&samplecrdv1.NFSVolume{}, f.defaultInformer)
}

func (f *nFSVolumeInformer) Lister() v1.NFSVolumeLister {
	return v1.NewNFSVolumeLister(f.Informer().GetIndexer())
}
